export default {
  SEARCH_WITH_TAGS: "@tools/SEARCH_WITH_TAGS",
  SEARCH_TOOLS: "@tools/SEARCH_TOOLS",
  LOAD_TOOLS: "@tools/LOAD_TOOLS",
  REMOVE_TOOL: "@tools/REMOVE_TOOL",
  RELOAD_TOOLS: "@tools/RELOAD_TOOLS",
  CREATE_TOOL: "@tools/CREATE_TOOL",
};
